name: Publish to ghcr

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to ghcr
        id: publish
        uses: duffney/wkg-github-action@9680cbd1dd38119bbc519c6c3e0b7fffe0b4982c
        with:
          file: rust_wasi_hello.wasm
          oci-reference-without-tag: ghcr.io/${{ github.actor }}/wasi-sample/rust-wasi-hello
          version: latest
      - name: print digest
        run: echo "The digest is ${{ steps.publish.outputs.digest }}"
      - name: print test
        run: echo "The test is ${{ steps.publish.outputs.test }}"
